main: not.savage.airheads.AirHeadsPlugin
version: 1.7.4
api-version: 1.21
name: ShockAirHeads
authors: [ Savage, SupremeVentures ]
depend: [ packetevents ]

commands:
  airheads:
    description: Interact with AirHeads in-game, and reload!
    usage: /airheads