main: not.savage.airheads.AirHeadsPlugin
version: 2.0.1
api-version: 1.21
name: ShockAirHeads
authors: [ Savage, SupremeVentures ]
softdepend: [ Multiverse-Core ]

commands:
  airheads:
    description: Interact with AirHeads in-game, and reload!
    usage: /airheads