main: not.savage.airheads.AirHeadsPlugin
version: 1.4.1
api-version: 1.21
name: ShockAirHeads
authors: [ Savage, SupremeVentures ]
depend: [ packetevents ]
softdepend: [ HologramBridge, DecentHolograms, HolographicDisplays, CMI ]

commands:
  airheads:
    description: Interact with AirHeads in-game, and reload!
    usage: /airheads