main: not.savage.airheads.AirHeadsPlugin
version: 2.1.2
api-version: 1.21
name: ShockAirHeads
authors: [ Savage, SupremeVentures ]
depend: [ PlaceholderAPI ]
softdepend: [ Multiverse-Core, packetevents ]
libraries:
  - net.kyori:adventure-api:4.22.0

commands:
  airheads:
    description: Interact with AirHeads in-game, and reload!
    usage: /airheads